# Generated by Django 2.2.5 on 2019-09-05 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
